# Copyright Avisto Telecom 2024

name: Docker Image CI

on:
    pull_request:
    push:
        branches: [main]

jobs:
    build:
        # On utilisera les runners fournis par Github.com par défaut
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
        runs-on: ubuntu-latest

        steps:
            # Utilise la dernière version
            - name: Checkout code
              uses: actions/checkout@vlatest

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@vlatest

            # Il faut créer deux secrets dans les paramètres de Github avec les identifiants de ton compte dockerhub
            - name: Login to DockerHub
              uses: docker/login-action@vlatest
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Choisis le nom de ton image
            # Modifie le code pour que l'image soit publiée sur dockerhub
            - name: Build and push
              uses: docker/build-push-action@vlatest
              with:
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/test:v1
